name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Only needed if you use Python code in your .qmd files
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python deps (if requirements.txt present)
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Set up Quarto (pinned version)
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.6.39'   # pin to avoid "latest" 404 issue

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: .

      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
